apiVersion: v1
kind: Service
metadata:
  name: my-native-app-service
spec:
  type: NodePort
  selector:
    app: my-native-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-native-app-deployment
  labels:
    app: my-native-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-native-app
  template:
    metadata:
      labels:
        app: my-native-app
    spec:
      containers:
        - name: nginx
          image: newnullboy/my-native-app
          ports:
            - containerPort: 80